# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'Visual Studio Enterprise(1b81c0f2-5820-4f8e-a92a-d714b6957750)'
    KeyVaultName: 'eo-test-keyvault'
    SecretsFilter: 'some-secret'

- pwsh: |
    # Install-PackageProvider -Name NuGet -Force -Scope CurrentUser
    # Find-Module -Name AzureRM.KeyVault -Repository PSGallery | Install-Module $_ -AcceptLicense

    Find-Module -Name AzureRM | Write-Host

    Find-Module -Name AzureRM.Profile | Install-Module $_ -AcceptLicense

    Find-Module -Name AzureRM | Write-Host

    $m = Find-Module -Name AzureRM.KeyVault -Repository PSGallery
    if($m -eq $null) { Write-Host 'Did not find AzureRM.KeyVault module!!' }
    Import-Module -Name AzureRM.KeyVault
    $secret = ConvertTo-SecureString -String "my-Awesome-password {(Get-Date).Second}" -AsPlainText -Force
    Set-AzureKeyVaultSecret -VaultName 'eo-test-keyvault' -Name 'some-secret' -SecretValue $secret
    Write-Host 'Done!'
  displayName: 'Update Secret in Vault'
  continueOnError: 'false'

- pwsh: |
    # Install-PackageProvider -Name NuGet -Force -Scope CurrentUser
    Find-Module -Name AzureRM.KeyVault | Install-Module $_ -AcceptLicense
    Import-Module -Name AzureRM.KeyVault
    $secret = Get-AzureKeyVaultSecret -VaultName 'eo-test-keyvault' -Name 'some-secret'
    Write-Host "The secret is {$secret.SecretValueText}."
  displayName: 'Display Secret in Vault'